-- ============================================================================
-- MIGRATION: ADD CLIENT_EVENT_ID & UNIQUE IDEMPOTENCY INDEX TO LEARNING_EVENTS
-- ============================================================================

-- 1. Add client_event_id column to store unique UUIDs generated by client
ALTER TABLE public.learning_events
ADD COLUMN IF NOT EXISTS client_event_id TEXT;

-- 2. Create unique partial index ensuring retry-safe telemetry insertion
-- Only non-null client_event_ids must be unique to allow legacy rows without client IDs
CREATE UNIQUE INDEX IF NOT EXISTS idx_learning_events_client_event_id
ON public.learning_events(client_event_id)
WHERE client_event_id IS NOT NULL;

-- 3. Ensure composite index for fast per-user event retrieval
CREATE INDEX IF NOT EXISTS idx_learning_events_user_type_created
ON public.learning_events(user_id, event_type, created_at DESC);
