-- 1. Create table for raw learning events
CREATE TABLE IF NOT EXISTS public.learning_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL, -- Nullable for guests
  topic_id BIGINT REFERENCES public.topics(id) ON DELETE CASCADE NOT NULL,
  event_type TEXT NOT NULL, -- 'visit', 'pass', 'fail'
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Indexes for fast aggregation
CREATE INDEX IF NOT EXISTS idx_learning_events_topic_id ON public.learning_events(topic_id);
CREATE INDEX IF NOT EXISTS idx_learning_events_event_type ON public.learning_events(event_type);

-- 3. Enable RLS
ALTER TABLE public.learning_events ENABLE ROW LEVEL SECURITY;

-- 4. Policies for RLS
CREATE POLICY "Allow public read learning_events" ON public.learning_events 
  FOR SELECT TO public USING (true);

CREATE POLICY "Allow public insert learning_events" ON public.learning_events 
  FOR INSERT TO public WITH CHECK (true);

-- 5. Consolidated view for real-time analytics calculations
CREATE OR REPLACE VIEW public.topic_analytics_view AS
SELECT 
  t.id AS topic_id,
  t.title AS topic_title,
  c.title AS chapter_title,
  s.name AS subject_name,
  s.id AS subject_id,
  COUNT(CASE WHEN le.event_type = 'visit' THEN 1 END) AS visit_count,
  COUNT(CASE WHEN le.event_type = 'pass' THEN 1 END) AS pass_count,
  COUNT(CASE WHEN le.event_type = 'fail' THEN 1 END) AS fail_count
FROM public.topics t
JOIN public.chapters c ON t.chapter_id = c.id
JOIN public.subjects s ON c.subject_id = s.id
LEFT JOIN public.learning_events le ON t.id = le.topic_id
GROUP BY t.id, t.title, c.title, s.name, s.id;
