-- ═══════════════════════════════════════════════════════════
-- TIXAR DATABASE EXTENSION & SECURITY MIGRATION
-- Compatible with the consolidated normalized schema
-- Idempotent & safe to run multiple times in Supabase SQL Editor
-- ═══════════════════════════════════════════════════════════

-- ==========================================================
-- 1. CREATE ADDITIONAL LEARNING TABLES
-- ==========================================================

-- User mistakes
CREATE TABLE IF NOT EXISTS public.user_mistakes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL
        REFERENCES public.profiles(id)
        ON DELETE CASCADE,
    topic_id BIGINT
        REFERENCES public.topics(id)
        ON DELETE SET NULL,
    topic_title TEXT,
    subject_id TEXT,
    chapter_id TEXT,
    chapter_key TEXT,
    question_index INTEGER DEFAULT 0,
    question_text TEXT,
    correct_answer TEXT,
    solution TEXT,
    user_answer TEXT,
    explanation TEXT,
    mistake_type TEXT,
    resolved BOOLEAN NOT NULL DEFAULT FALSE,
    resolved_at TIMESTAMP WITH TIME ZONE,
    attempt_count INTEGER DEFAULT 1,
    created_at TIMESTAMP WITH TIME ZONE
        DEFAULT timezone('utc'::text, now())
        NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE
        DEFAULT timezone('utc'::text, now())
        NOT NULL
);

-- Spaced repetition reviews
CREATE TABLE IF NOT EXISTS public.spaced_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL
        REFERENCES public.profiles(id)
        ON DELETE CASCADE,
    topic_id BIGINT
        REFERENCES public.topics(id)
        ON DELETE SET NULL,
    topic_title TEXT,
    subject_id TEXT
        REFERENCES public.subjects(id)
        ON DELETE SET NULL,
    chapter_id TEXT,
    next_review TIMESTAMP WITH TIME ZONE,
    next_review_at TIMESTAMP WITH TIME ZONE,
    interval_days INTEGER DEFAULT 1,
    repetitions INTEGER DEFAULT 0,
    ease_factor NUMERIC DEFAULT 2.5,
    last_reviewed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE
        DEFAULT timezone('utc'::text, now())
        NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE
        DEFAULT timezone('utc'::text, now())
        NOT NULL
);

-- User notes
CREATE TABLE IF NOT EXISTS public.user_notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL
        REFERENCES public.profiles(id)
        ON DELETE CASCADE,
    topic_id BIGINT
        REFERENCES public.topics(id)
        ON DELETE SET NULL,
    topic_title TEXT,
    subject_id TEXT
        REFERENCES public.subjects(id)
        ON DELETE SET NULL,
    chapter_id TEXT,
    note_text TEXT DEFAULT '',
    content TEXT DEFAULT '',
    created_at TIMESTAMP WITH TIME ZONE
        DEFAULT timezone('utc'::text, now())
        NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE
        DEFAULT timezone('utc'::text, now())
        NOT NULL
);

-- Learning events
CREATE TABLE IF NOT EXISTS public.learning_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL
        REFERENCES public.profiles(id)
        ON DELETE CASCADE,
    event_type TEXT NOT NULL,
    subject_id TEXT
        REFERENCES public.subjects(id)
        ON DELETE SET NULL,
    topic_id BIGINT
        REFERENCES public.topics(id)
        ON DELETE SET NULL,
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE
        DEFAULT timezone('utc'::text, now())
        NOT NULL
);

-- ==========================================================
-- 2. EXTEND PROGRESS TABLE
-- ==========================================================

ALTER TABLE public.progress
    ADD COLUMN IF NOT EXISTS topic_title TEXT,
    ADD COLUMN IF NOT EXISTS subject_id TEXT
        REFERENCES public.subjects(id)
        ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS chapter_id TEXT,
    ADD COLUMN IF NOT EXISTS confidence_level TEXT
        CHECK (
            confidence_level IN ('low', 'medium', 'high')
        ),
    ADD COLUMN IF NOT EXISTS mastered BOOLEAN
        NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS mastered_at TIMESTAMP WITH TIME ZONE;

-- ==========================================================
-- 3. ENABLE RLS
-- ==========================================================

ALTER TABLE public.progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_mistakes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.spaced_reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.learning_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.achievements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.enrollments ENABLE ROW LEVEL SECURITY;

-- ==========================================================
-- 4. REMOVE OLD CONFLICTING POLICIES
-- ==========================================================

-- Progress
DROP POLICY IF EXISTS "Allow users to read own progress" ON public.progress;
DROP POLICY IF EXISTS "Allow users to insert own progress" ON public.progress;
DROP POLICY IF EXISTS "Allow users to update own progress" ON public.progress;
DROP POLICY IF EXISTS "Users isolated progress all" ON public.progress;

-- Enrollments
DROP POLICY IF EXISTS "Allow users to read own enrollments" ON public.enrollments;
DROP POLICY IF EXISTS "Allow users to insert own enrollments" ON public.enrollments;
DROP POLICY IF EXISTS "Allow users to delete own enrollments" ON public.enrollments;
DROP POLICY IF EXISTS "Users isolated enrollments all" ON public.enrollments;

-- Achievements
DROP POLICY IF EXISTS "Allow users to read own achievements" ON public.achievements;
DROP POLICY IF EXISTS "Users isolated achievements all" ON public.achievements;

-- ==========================================================
-- 5. CREATE CLEAN USER-ISOLATION POLICIES
-- ==========================================================

-- Progress
CREATE POLICY "Users isolated progress all"
ON public.progress
FOR ALL
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- User mistakes
DROP POLICY IF EXISTS "Users isolated mistakes all" ON public.user_mistakes;
CREATE POLICY "Users isolated mistakes all"
ON public.user_mistakes
FOR ALL
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- Spaced reviews
DROP POLICY IF EXISTS "Users isolated spaced_reviews all" ON public.spaced_reviews;
CREATE POLICY "Users isolated spaced_reviews all"
ON public.spaced_reviews
FOR ALL
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- User notes
DROP POLICY IF EXISTS "Users isolated user_notes all" ON public.user_notes;
CREATE POLICY "Users isolated user_notes all"
ON public.user_notes
FOR ALL
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- Learning events
DROP POLICY IF EXISTS "Users isolated learning_events all" ON public.learning_events;
CREATE POLICY "Users isolated learning_events all"
ON public.learning_events
FOR ALL
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- Achievements
DROP POLICY IF EXISTS "Users isolated achievements all" ON public.achievements;
CREATE POLICY "Users isolated achievements all"
ON public.achievements
FOR ALL
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- Enrollments
DROP POLICY IF EXISTS "Users isolated enrollments all" ON public.enrollments;
CREATE POLICY "Users isolated enrollments all"
ON public.enrollments
FOR ALL
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- ==========================================================
-- 6. PERFORMANCE INDEXES
-- ==========================================================

CREATE INDEX IF NOT EXISTS idx_user_mistakes_user_id ON public.user_mistakes(user_id);
CREATE INDEX IF NOT EXISTS idx_spaced_reviews_user_id ON public.spaced_reviews(user_id);
CREATE INDEX IF NOT EXISTS idx_user_notes_user_id ON public.user_notes(user_id);
CREATE INDEX IF NOT EXISTS idx_learning_events_user_id ON public.learning_events(user_id);
CREATE INDEX IF NOT EXISTS idx_learning_events_created_at ON public.learning_events(created_at);

-- ==========================================================
-- 7. VERIFY ACTIVE RLS POLICIES
-- ==========================================================

SELECT
    schemaname,
    tablename,
    policyname,
    roles,
    cmd
FROM pg_policies
WHERE schemaname = 'public'
ORDER BY tablename, policyname;
