-- ═══════════════════════════════════════════════════════════════════════
-- MIGRATION: Fix User Progress Storage, Data Isolation & All Tables
-- Run this in Supabase SQL Editor
-- This is SAFE to run multiple times (idempotent)
-- ═══════════════════════════════════════════════════════════════════════

-- ─────────────────────────────────────────────────────────────
-- 1. Ensure Profile Auto-Creation Trigger is Active & Robust
-- ─────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, email, username, full_name, avatar_url, role_name)
  VALUES (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'username', split_part(new.email, '@', 1)),
    coalesce(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name', ''),
    coalesce(new.raw_user_meta_data->>'avatar_url', new.raw_user_meta_data->>'picture', ''),
    'student'
  )
  ON CONFLICT (id) DO UPDATE
  SET
    email = excluded.email,
    username = coalesce(excluded.username, profiles.username),
    full_name = coalesce(excluded.full_name, profiles.full_name),
    avatar_url = coalesce(excluded.avatar_url, profiles.avatar_url),
    updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT OR UPDATE OF email, raw_user_meta_data ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Backfill missing profiles for existing auth users
INSERT INTO public.profiles (id, email, username, full_name, role_name)
SELECT 
  id, 
  email, 
  split_part(email, '@', 1), 
  coalesce(raw_user_meta_data->>'full_name', split_part(email, '@', 1)), 
  'student'
FROM auth.users
ON CONFLICT (id) DO NOTHING;

-- ─────────────────────────────────────────────────────────────
-- 2. Extend progress table with mastery columns (idempotent)
-- ─────────────────────────────────────────────────────────────
ALTER TABLE public.progress
  ADD COLUMN IF NOT EXISTS confidence_level TEXT CHECK (confidence_level IN ('low','medium','high')),
  ADD COLUMN IF NOT EXISTS mastered BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS mastered_at TIMESTAMP WITH TIME ZONE;

-- ─────────────────────────────────────────────────────────────
-- 3. User Mistakes Table
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.user_mistakes (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     UUID   REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  topic_id    BIGINT REFERENCES public.topics(id)   ON DELETE CASCADE,
  subject_id  TEXT,
  chapter_key TEXT,
  question_index INTEGER NOT NULL,
  question_text   TEXT DEFAULT '',
  correct_answer  TEXT DEFAULT '',
  solution        TEXT DEFAULT '',
  resolved        BOOLEAN DEFAULT FALSE,
  resolved_at     TIMESTAMP WITH TIME ZONE,
  attempt_count   INTEGER DEFAULT 1,
  created_at      TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at      TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  CONSTRAINT user_mistakes_user_topic_q_unique UNIQUE (user_id, topic_id, question_index)
);

CREATE INDEX IF NOT EXISTS idx_user_mistakes_user_id     ON public.user_mistakes(user_id);
CREATE INDEX IF NOT EXISTS idx_user_mistakes_topic_id    ON public.user_mistakes(topic_id);
CREATE INDEX IF NOT EXISTS idx_user_mistakes_resolved    ON public.user_mistakes(resolved);
CREATE INDEX IF NOT EXISTS idx_user_mistakes_subject_id  ON public.user_mistakes(subject_id);

-- ─────────────────────────────────────────────────────────────
-- 4. Spaced Reviews Table
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.spaced_reviews (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       UUID   REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  topic_id      BIGINT REFERENCES public.topics(id)   ON DELETE CASCADE NOT NULL,
  next_review_at TIMESTAMP WITH TIME ZONE NOT NULL,
  interval_days  INTEGER DEFAULT 1,
  ease_factor    NUMERIC(4,2) DEFAULT 2.50,
  repetitions    INTEGER DEFAULT 0,
  created_at     TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at     TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  CONSTRAINT spaced_reviews_user_topic_unique UNIQUE (user_id, topic_id)
);

CREATE INDEX IF NOT EXISTS idx_spaced_reviews_user_id        ON public.spaced_reviews(user_id);
CREATE INDEX IF NOT EXISTS idx_spaced_reviews_next_review_at ON public.spaced_reviews(next_review_at);

-- ─────────────────────────────────────────────────────────────
-- 5. User Notes Table
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.user_notes (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    UUID   REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  topic_id   BIGINT REFERENCES public.topics(id)   ON DELETE CASCADE NOT NULL,
  note_text  TEXT   NOT NULL DEFAULT '',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  CONSTRAINT user_notes_user_topic_unique UNIQUE (user_id, topic_id)
);

CREATE INDEX IF NOT EXISTS idx_user_notes_user_id  ON public.user_notes(user_id);
CREATE INDEX IF NOT EXISTS idx_user_notes_topic_id ON public.user_notes(topic_id);

-- ─────────────────────────────────────────────────────────────
-- 6. Learning Events Table (for analytics)
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.learning_events (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    UUID   REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  topic_id   BIGINT REFERENCES public.topics(id)   ON DELETE CASCADE NOT NULL,
  event_type TEXT   NOT NULL,
  timestamp  TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_learning_events_user_id   ON public.learning_events(user_id);
CREATE INDEX IF NOT EXISTS idx_learning_events_topic_id  ON public.learning_events(topic_id);

-- ─────────────────────────────────────────────────────────────
-- 7. User Review Queue VIEW — Due topics for each user
-- ─────────────────────────────────────────────────────────────
CREATE OR REPLACE VIEW public.user_review_queue AS
SELECT
  sr.user_id,
  sr.topic_id,
  t.title    AS topic_title,
  c.title    AS chapter_title,
  c.chapter_key,
  s.id       AS subject_id,
  s.name     AS subject_name,
  sr.next_review_at,
  sr.interval_days,
  sr.ease_factor,
  sr.repetitions
FROM public.spaced_reviews sr
JOIN public.topics   t ON t.id = sr.topic_id
JOIN public.chapters c ON c.id = t.chapter_id
JOIN public.subjects s ON s.id = c.subject_id
WHERE sr.next_review_at <= now();

-- ─────────────────────────────────────────────────────────────
-- 8. Auto-update updated_at on user tables
-- ─────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = timezone('utc', now());
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_user_mistakes_updated_at  ON public.user_mistakes;
CREATE TRIGGER trg_user_mistakes_updated_at
  BEFORE UPDATE ON public.user_mistakes
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS trg_spaced_reviews_updated_at ON public.spaced_reviews;
CREATE TRIGGER trg_spaced_reviews_updated_at
  BEFORE UPDATE ON public.spaced_reviews
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS trg_user_notes_updated_at ON public.user_notes;
CREATE TRIGGER trg_user_notes_updated_at
  BEFORE UPDATE ON public.user_notes
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS trg_progress_updated_at ON public.progress;
CREATE TRIGGER trg_progress_updated_at
  BEFORE UPDATE ON public.progress
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ─────────────────────────────────────────────────────────────
-- 9. Enable RLS on all user data tables
-- ─────────────────────────────────────────────────────────────
ALTER TABLE public.progress         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_mistakes    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.spaced_reviews   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_notes       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.learning_events  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.achievements     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.enrollments      ENABLE ROW LEVEL SECURITY;

-- ─────────────────────────────────────────────────────────────
-- 10. Progress Policies (strict user isolation)
-- ─────────────────────────────────────────────────────────────
DROP POLICY IF EXISTS "Allow users to read own progress"   ON public.progress;
DROP POLICY IF EXISTS "Allow users to insert own progress" ON public.progress;
DROP POLICY IF EXISTS "Allow users to update own progress" ON public.progress;
DROP POLICY IF EXISTS "Users isolated progress select"     ON public.progress;
DROP POLICY IF EXISTS "Users isolated progress insert"     ON public.progress;
DROP POLICY IF EXISTS "Users isolated progress update"     ON public.progress;

CREATE POLICY "Users isolated progress select" ON public.progress
  FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Users isolated progress insert" ON public.progress
  FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users isolated progress update" ON public.progress
  FOR UPDATE TO authenticated USING (auth.uid() = user_id);

-- ─────────────────────────────────────────────────────────────
-- 11. User Mistakes Policies
-- ─────────────────────────────────────────────────────────────
DROP POLICY IF EXISTS "Users read own mistakes"      ON public.user_mistakes;
DROP POLICY IF EXISTS "Users insert own mistakes"    ON public.user_mistakes;
DROP POLICY IF EXISTS "Users update own mistakes"    ON public.user_mistakes;
DROP POLICY IF EXISTS "Users delete own mistakes"    ON public.user_mistakes;
DROP POLICY IF EXISTS "Users isolated mistakes all"  ON public.user_mistakes;

CREATE POLICY "Users isolated mistakes all" ON public.user_mistakes
  FOR ALL TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- ─────────────────────────────────────────────────────────────
-- 12. Spaced Reviews Policies
-- ─────────────────────────────────────────────────────────────
DROP POLICY IF EXISTS "Users read own spaced_reviews"      ON public.spaced_reviews;
DROP POLICY IF EXISTS "Users upsert own spaced_reviews"    ON public.spaced_reviews;
DROP POLICY IF EXISTS "Users update own spaced_reviews"    ON public.spaced_reviews;
DROP POLICY IF EXISTS "Users isolated spaced_reviews all"  ON public.spaced_reviews;

CREATE POLICY "Users isolated spaced_reviews all" ON public.spaced_reviews
  FOR ALL TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- ─────────────────────────────────────────────────────────────
-- 13. User Notes Policies
-- ─────────────────────────────────────────────────────────────
DROP POLICY IF EXISTS "Users read own notes"      ON public.user_notes;
DROP POLICY IF EXISTS "Users upsert own notes"    ON public.user_notes;
DROP POLICY IF EXISTS "Users update own notes"    ON public.user_notes;
DROP POLICY IF EXISTS "Users isolated user_notes all" ON public.user_notes;

CREATE POLICY "Users isolated user_notes all" ON public.user_notes
  FOR ALL TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- ─────────────────────────────────────────────────────────────
-- 14. Learning Events Policies
-- ─────────────────────────────────────────────────────────────
DROP POLICY IF EXISTS "Users isolated learning_events all" ON public.learning_events;

CREATE POLICY "Users isolated learning_events all" ON public.learning_events
  FOR ALL TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- ─────────────────────────────────────────────────────────────
-- 15. Achievements Policies
--     Allow INSERT only (no duplicates) + SELECT for owner
-- ─────────────────────────────────────────────────────────────
DROP POLICY IF EXISTS "Allow users to read own achievements" ON public.achievements;
DROP POLICY IF EXISTS "Users isolated achievements all"      ON public.achievements;
DROP POLICY IF EXISTS "Users achievements select"            ON public.achievements;
DROP POLICY IF EXISTS "Users achievements insert"            ON public.achievements;

CREATE POLICY "Users achievements select" ON public.achievements
  FOR SELECT TO authenticated USING (auth.uid() = user_id);

CREATE POLICY "Users achievements insert" ON public.achievements
  FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);

-- ─────────────────────────────────────────────────────────────
-- 16. Enrollments Policies
-- ─────────────────────────────────────────────────────────────
DROP POLICY IF EXISTS "Allow users to read own enrollments"   ON public.enrollments;
DROP POLICY IF EXISTS "Allow users to insert own enrollments" ON public.enrollments;
DROP POLICY IF EXISTS "Allow users to delete own enrollments" ON public.enrollments;
DROP POLICY IF EXISTS "Users isolated enrollments all"        ON public.enrollments;

CREATE POLICY "Users isolated enrollments all" ON public.enrollments
  FOR ALL TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- ─────────────────────────────────────────────────────────────
-- 17. Profiles Policy — Users can insert their own profile row
--     (needed by backfill / when trigger fires AFTER login)
-- ─────────────────────────────────────────────────────────────
DROP POLICY IF EXISTS "Users can insert own profile" ON public.profiles;
CREATE POLICY "Users can insert own profile" ON public.profiles
  FOR INSERT TO authenticated WITH CHECK (auth.uid() = id);

-- ─────────────────────────────────────────────────────────────
-- DONE — All tables, indexes, RLS policies, and views are set up
-- ─────────────────────────────────────────────────────────────
