-- ═══════════════════════════════════════════════════════════════════════
-- MIGRATION: Learning Features — User Mistakes, Spaced Reviews, User Notes
-- Run this in Supabase SQL Editor AFTER schema.sql has been applied
-- ═══════════════════════════════════════════════════════════════════════

-- ─────────────────────────────────────────────────────────────
-- TABLE 1: user_mistakes
-- Stores every question a user answered incorrectly so they can
-- revisit and practice them in the Mistake Journal.
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.user_mistakes (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     UUID   REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  topic_id    BIGINT REFERENCES public.topics(id)   ON DELETE CASCADE NOT NULL,
  subject_id  TEXT   REFERENCES public.subjects(id) ON DELETE CASCADE NOT NULL,
  chapter_key TEXT   NOT NULL,
  question_index INTEGER NOT NULL,
  question_text   TEXT,
  correct_answer  TEXT,
  solution        TEXT,
  resolved        BOOLEAN NOT NULL DEFAULT FALSE,
  attempt_count   INTEGER NOT NULL DEFAULT 1,
  resolved_at     TIMESTAMP WITH TIME ZONE,
  created_at      TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()) NOT NULL,
  updated_at      TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()) NOT NULL,
  CONSTRAINT user_mistakes_unique UNIQUE (user_id, topic_id, question_index)
);

CREATE INDEX IF NOT EXISTS idx_user_mistakes_user_id     ON public.user_mistakes(user_id);
CREATE INDEX IF NOT EXISTS idx_user_mistakes_topic_id    ON public.user_mistakes(topic_id);
CREATE INDEX IF NOT EXISTS idx_user_mistakes_resolved    ON public.user_mistakes(resolved);
CREATE INDEX IF NOT EXISTS idx_user_mistakes_subject_id  ON public.user_mistakes(subject_id);

-- ─────────────────────────────────────────────────────────────
-- TABLE 2: spaced_reviews
-- One row per (user, topic) tracking the SM-2 spaced repetition
-- schedule: next review date, interval, ease factor, repetitions.
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.spaced_reviews (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       UUID   REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  topic_id      BIGINT REFERENCES public.topics(id)   ON DELETE CASCADE NOT NULL,
  next_review_at TIMESTAMP WITH TIME ZONE NOT NULL,
  interval_days  INTEGER NOT NULL DEFAULT 1,
  ease_factor    NUMERIC(4,2) NOT NULL DEFAULT 2.50,
  repetitions    INTEGER NOT NULL DEFAULT 0,
  updated_at     TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()) NOT NULL,
  CONSTRAINT spaced_reviews_user_topic_unique UNIQUE (user_id, topic_id)
);

CREATE INDEX IF NOT EXISTS idx_spaced_reviews_user_id        ON public.spaced_reviews(user_id);
CREATE INDEX IF NOT EXISTS idx_spaced_reviews_next_review_at ON public.spaced_reviews(next_review_at);

-- ─────────────────────────────────────────────────────────────
-- TABLE 3: user_notes
-- Personal synthesis scratchpad text saved per (user, topic).
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.user_notes (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    UUID   REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  topic_id   BIGINT REFERENCES public.topics(id)   ON DELETE CASCADE NOT NULL,
  note_text  TEXT   NOT NULL DEFAULT '',
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()) NOT NULL,
  CONSTRAINT user_notes_user_topic_unique UNIQUE (user_id, topic_id)
);

CREATE INDEX IF NOT EXISTS idx_user_notes_user_id  ON public.user_notes(user_id);
CREATE INDEX IF NOT EXISTS idx_user_notes_topic_id ON public.user_notes(topic_id);

-- ─────────────────────────────────────────────────────────────
-- ENROLLMENTS: already in schema.sql — only add missing indexes
-- ─────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_enrollments_subject_id ON public.enrollments(subject_id);

-- ─────────────────────────────────────────────────────────────
-- ROW LEVEL SECURITY
-- ─────────────────────────────────────────────────────────────
ALTER TABLE public.user_mistakes  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.spaced_reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_notes     ENABLE ROW LEVEL SECURITY;

-- Drop before recreate for idempotency
DROP POLICY IF EXISTS "Users read own mistakes"      ON public.user_mistakes;
DROP POLICY IF EXISTS "Users insert own mistakes"    ON public.user_mistakes;
DROP POLICY IF EXISTS "Users update own mistakes"    ON public.user_mistakes;
DROP POLICY IF EXISTS "Users delete own mistakes"    ON public.user_mistakes;

DROP POLICY IF EXISTS "Users read own spaced_reviews"   ON public.spaced_reviews;
DROP POLICY IF EXISTS "Users upsert own spaced_reviews" ON public.spaced_reviews;
DROP POLICY IF EXISTS "Users update own spaced_reviews" ON public.spaced_reviews;

DROP POLICY IF EXISTS "Users read own notes"   ON public.user_notes;
DROP POLICY IF EXISTS "Users upsert own notes" ON public.user_notes;
DROP POLICY IF EXISTS "Users update own notes" ON public.user_notes;

-- user_mistakes policies
CREATE POLICY "Users read own mistakes"   ON public.user_mistakes FOR SELECT    TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Users insert own mistakes" ON public.user_mistakes FOR INSERT    TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users update own mistakes" ON public.user_mistakes FOR UPDATE    TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Users delete own mistakes" ON public.user_mistakes FOR DELETE    TO authenticated USING (auth.uid() = user_id);

-- spaced_reviews policies
CREATE POLICY "Users read own spaced_reviews"   ON public.spaced_reviews FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Users upsert own spaced_reviews" ON public.spaced_reviews FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users update own spaced_reviews" ON public.spaced_reviews FOR UPDATE TO authenticated USING (auth.uid() = user_id);

-- user_notes policies
CREATE POLICY "Users read own notes"   ON public.user_notes FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Users upsert own notes" ON public.user_notes FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users update own notes" ON public.user_notes FOR UPDATE TO authenticated USING (auth.uid() = user_id);

-- ─────────────────────────────────────────────────────────────
-- HELPER: auto-update updated_at on user_mistakes and spaced_reviews
-- ─────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = timezone('utc', now());
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_user_mistakes_updated_at  ON public.user_mistakes;
CREATE TRIGGER trg_user_mistakes_updated_at
  BEFORE UPDATE ON public.user_mistakes
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS trg_spaced_reviews_updated_at ON public.spaced_reviews;
CREATE TRIGGER trg_spaced_reviews_updated_at
  BEFORE UPDATE ON public.spaced_reviews
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS trg_user_notes_updated_at ON public.user_notes;
CREATE TRIGGER trg_user_notes_updated_at
  BEFORE UPDATE ON public.user_notes
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ─────────────────────────────────────────────────────────────
-- PROGRESS TABLE: add confidence_level and mastered columns
-- if they don't already exist
-- ─────────────────────────────────────────────────────────────
ALTER TABLE public.progress
  ADD COLUMN IF NOT EXISTS confidence_level TEXT CHECK (confidence_level IN ('low','medium','high')),
  ADD COLUMN IF NOT EXISTS mastered BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS mastered_at TIMESTAMP WITH TIME ZONE;

-- ─────────────────────────────────────────────────────────────
-- VIEW: user_review_queue
-- Fast query for the "Due for Review" queue on the Subjects page
-- and Analytics Dashboard
-- ─────────────────────────────────────────────────────────────
CREATE OR REPLACE VIEW public.user_review_queue AS
SELECT
  sr.user_id,
  sr.topic_id,
  t.title    AS topic_title,
  c.title    AS chapter_title,
  c.chapter_key,
  s.id       AS subject_id,
  s.name     AS subject_name,
  sr.next_review_at,
  sr.interval_days,
  sr.ease_factor,
  sr.repetitions
FROM public.spaced_reviews sr
JOIN public.topics   t ON t.id = sr.topic_id
JOIN public.chapters c ON c.id = t.chapter_id
JOIN public.subjects s ON s.id = c.subject_id
WHERE sr.next_review_at <= now();
