-- ─────────────────────────────────────────────────────────────
-- Supabase Database Restructuring for 100% User Data Privacy
-- Run this script in your Supabase SQL Editor
-- ─────────────────────────────────────────────────────────────

-- 1. Ensure Profile Auto-Creation Trigger is Active & Robust
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, email, username, full_name, avatar_url, role_name)
  VALUES (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'username', split_part(new.email, '@', 1)),
    coalesce(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name', ''),
    coalesce(new.raw_user_meta_data->>'avatar_url', new.raw_user_meta_data->>'picture', ''),
    'student'
  )
  ON CONFLICT (id) DO UPDATE
  SET
    email = excluded.email,
    username = coalesce(excluded.username, profiles.username),
    full_name = coalesce(excluded.full_name, profiles.full_name),
    avatar_url = coalesce(excluded.avatar_url, profiles.avatar_url),
    updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT OR UPDATE OF email, raw_user_meta_data ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Backfill missing profiles for existing auth users
INSERT INTO public.profiles (id, email, username, full_name, role_name)
SELECT 
  id, 
  email, 
  split_part(email, '@', 1), 
  coalesce(raw_user_meta_data->>'full_name', split_part(email, '@', 1)), 
  'student'
FROM auth.users
ON CONFLICT (id) DO NOTHING;

-- 2. Create Learning Feature Tables if not present with user_id Foreign Keys
CREATE TABLE IF NOT EXISTS public.user_mistakes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  topic_id BIGINT REFERENCES public.topics(id) ON DELETE CASCADE,
  subject_id TEXT,
  chapter_key TEXT,
  question_index INTEGER NOT NULL,
  question_text TEXT DEFAULT '',
  correct_answer TEXT DEFAULT '',
  solution TEXT DEFAULT '',
  resolved BOOLEAN DEFAULT FALSE,
  resolved_at TIMESTAMP WITH TIME ZONE,
  attempt_count INTEGER DEFAULT 1,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  CONSTRAINT user_mistakes_user_topic_q_unique UNIQUE (user_id, topic_id, question_index)
);

CREATE TABLE IF NOT EXISTS public.spaced_reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  topic_id BIGINT REFERENCES public.topics(id) ON DELETE CASCADE NOT NULL,
  next_review_at TIMESTAMP WITH TIME ZONE NOT NULL,
  interval_days INTEGER DEFAULT 1,
  ease_factor NUMERIC(4,2) DEFAULT 2.50,
  repetitions INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  CONSTRAINT spaced_reviews_user_topic_unique UNIQUE (user_id, topic_id)
);

CREATE TABLE IF NOT EXISTS public.user_notes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  topic_id BIGINT REFERENCES public.topics(id) ON DELETE CASCADE NOT NULL,
  note_text TEXT DEFAULT '',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  CONSTRAINT user_notes_user_topic_unique UNIQUE (user_id, topic_id)
);

CREATE TABLE IF NOT EXISTS public.learning_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  topic_id BIGINT REFERENCES public.topics(id) ON DELETE CASCADE NOT NULL,
  event_type TEXT NOT NULL,
  timestamp TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Enable RLS on all user data tables
ALTER TABLE public.progress         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_mistakes    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.spaced_reviews   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_notes       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.learning_events  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.achievements     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.enrollments      ENABLE ROW LEVEL SECURITY;

-- 4. Apply strict user isolation RLS policies
DROP POLICY IF EXISTS "Users isolated progress select" ON public.progress;
DROP POLICY IF EXISTS "Users isolated progress insert" ON public.progress;
DROP POLICY IF EXISTS "Users isolated progress update" ON public.progress;
CREATE POLICY "Users isolated progress select" ON public.progress FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Users isolated progress insert" ON public.progress FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users isolated progress update" ON public.progress FOR UPDATE TO authenticated USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users isolated mistakes all" ON public.user_mistakes;
CREATE POLICY "Users isolated mistakes all" ON public.user_mistakes FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users isolated spaced_reviews all" ON public.spaced_reviews;
CREATE POLICY "Users isolated spaced_reviews all" ON public.spaced_reviews FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users isolated user_notes all" ON public.user_notes;
CREATE POLICY "Users isolated user_notes all" ON public.user_notes FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users isolated learning_events all" ON public.learning_events;
CREATE POLICY "Users isolated learning_events all" ON public.learning_events FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users isolated achievements all" ON public.achievements;
CREATE POLICY "Users isolated achievements all" ON public.achievements FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users isolated enrollments all" ON public.enrollments;
CREATE POLICY "Users isolated enrollments all" ON public.enrollments FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
