-- Consolidated normalized schema for Shifter/Tixar (Supabase)
-- Drop existing views and tables if they exist in dependency order
DROP VIEW IF EXISTS public.content_view CASCADE;
DROP TABLE IF EXISTS public.lesson_versions CASCADE;
DROP TABLE IF EXISTS public.lessons CASCADE;
DROP TABLE IF EXISTS public.answers CASCADE;
DROP TABLE IF EXISTS public.questions CASCADE;
DROP TABLE IF EXISTS public.quizzes CASCADE;
DROP TABLE IF EXISTS public.progress CASCADE;
DROP TABLE IF EXISTS public.enrollments CASCADE;
DROP TABLE IF EXISTS public.achievements CASCADE;
DROP TABLE IF EXISTS public.audit_logs CASCADE;
DROP TABLE IF EXISTS public.topics CASCADE;
DROP TABLE IF EXISTS public.chapters CASCADE;
DROP TABLE IF EXISTS public.subjects CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;
DROP TABLE IF EXISTS public.roles CASCADE;
DROP TABLE IF EXISTS public.content CASCADE;
DROP TABLE IF EXISTS public.curriculum CASCADE;

-- 1. Roles table
CREATE TABLE public.roles (
  role_name TEXT PRIMARY KEY
);

-- Insert standard roles
INSERT INTO public.roles (role_name) VALUES 
  ('admin'), 
  ('teacher'), 
  ('student'), 
  ('moderator')
ON CONFLICT DO NOTHING;

-- 2. Profiles table
CREATE TABLE public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  email TEXT UNIQUE,
  username TEXT,
  full_name TEXT,
  avatar_url TEXT,
  role_name TEXT REFERENCES public.roles(role_name) DEFAULT 'student',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Subjects table
CREATE TABLE public.subjects (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Chapters table
CREATE TABLE public.chapters (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subject_id TEXT REFERENCES public.subjects(id) ON DELETE CASCADE,
  chapter_key TEXT NOT NULL,
  title TEXT NOT NULL,
  position INTEGER NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  CONSTRAINT chapters_subject_key_unique UNIQUE (subject_id, chapter_key)
);

-- 5. Topics table
CREATE TABLE public.topics (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chapter_id BIGINT REFERENCES public.chapters(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  position INTEGER NOT NULL,
  difficulty TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  CONSTRAINT topics_chapter_title_unique UNIQUE (chapter_id, title)
);

-- 6. Lessons table
CREATE TABLE public.lessons (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  topic_id BIGINT REFERENCES public.topics(id) ON DELETE CASCADE UNIQUE,
  content TEXT NOT NULL,
  summary TEXT,
  estimated_minutes INTEGER,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 7. Lesson Versions table (for content versioning)
CREATE TABLE public.lesson_versions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lesson_id BIGINT REFERENCES public.lessons(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  version INTEGER NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 8. Quizzes table
CREATE TABLE public.quizzes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  topic_id BIGINT REFERENCES public.topics(id) ON DELETE CASCADE UNIQUE,
  title TEXT,
  passing_score INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 9. Questions table
CREATE TABLE public.questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quiz_id BIGINT REFERENCES public.quizzes(id) ON DELETE CASCADE,
  question TEXT NOT NULL,
  type TEXT DEFAULT 'text',
  points INTEGER DEFAULT 1,
  hint TEXT,
  explain TEXT,
  position INTEGER NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 10. Answers table
CREATE TABLE public.answers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question_id BIGINT REFERENCES public.questions(id) ON DELETE CASCADE,
  answer_text TEXT NOT NULL,
  is_correct BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 11. Enrollments table
CREATE TABLE public.enrollments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  subject_id TEXT REFERENCES public.subjects(id) ON DELETE CASCADE,
  enrolled_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  CONSTRAINT enrollments_user_subject_unique UNIQUE (user_id, subject_id)
);

-- 12. User Progress table
CREATE TABLE public.progress (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  topic_id BIGINT REFERENCES public.topics(id) ON DELETE CASCADE,
  completed BOOLEAN NOT NULL DEFAULT FALSE,
  score INTEGER,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  CONSTRAINT progress_user_topic_unique UNIQUE (user_id, topic_id)
);

-- 13. Achievements table
CREATE TABLE public.achievements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  achievement_name TEXT NOT NULL,
  unlocked_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 14. Audit Logs table
CREATE TABLE public.audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  action TEXT NOT NULL,
  table_name TEXT NOT NULL,
  record_id TEXT NOT NULL,
  timestamp TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create a legacy mapping view for notes and topics to simplify query layers
CREATE OR REPLACE VIEW public.content_view AS
SELECT 
  s.id AS sid,
  c.chapter_key AS cid,
  t.title AS topic,
  l.content AS notes,
  t.id AS topic_id
FROM public.topics t
JOIN public.chapters c ON t.chapter_id = c.id
JOIN public.subjects s ON c.subject_id = s.id
LEFT JOIN public.lessons l ON l.topic_id = t.id;

-- Indexes for scaling performance
CREATE INDEX IF NOT EXISTS idx_chapters_subject_id ON public.chapters(subject_id);
CREATE INDEX IF NOT EXISTS idx_topics_chapter_id ON public.topics(chapter_id);
CREATE INDEX IF NOT EXISTS idx_lessons_topic_id ON public.lessons(topic_id);
CREATE INDEX IF NOT EXISTS idx_quizzes_topic_id ON public.quizzes(topic_id);
CREATE INDEX IF NOT EXISTS idx_questions_quiz_id ON public.questions(quiz_id);
CREATE INDEX IF NOT EXISTS idx_answers_question_id ON public.answers(question_id);
CREATE INDEX IF NOT EXISTS idx_progress_user_id ON public.progress(user_id);
CREATE INDEX IF NOT EXISTS idx_enrollments_user_id ON public.enrollments(user_id);

-- Enable Row Level Security (RLS) on all tables
ALTER TABLE public.roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subjects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chapters ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.topics ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lessons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lesson_versions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quizzes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.answers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.enrollments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.achievements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist (for idempotency)
DROP POLICY IF EXISTS "Allow public read" ON public.roles;
DROP POLICY IF EXISTS "Allow public read" ON public.profiles;
DROP POLICY IF EXISTS "Allow public read" ON public.subjects;
DROP POLICY IF EXISTS "Allow public read" ON public.chapters;
DROP POLICY IF EXISTS "Allow public read" ON public.topics;
DROP POLICY IF EXISTS "Allow public read" ON public.lessons;
DROP POLICY IF EXISTS "Allow public read" ON public.lesson_versions;
DROP POLICY IF EXISTS "Allow public read" ON public.quizzes;
DROP POLICY IF EXISTS "Allow public read" ON public.questions;
DROP POLICY IF EXISTS "Allow public read" ON public.answers;
DROP POLICY IF EXISTS "Allow users to update own profile" ON public.profiles;
DROP POLICY IF EXISTS "Allow users to read own enrollments" ON public.enrollments;
DROP POLICY IF EXISTS "Allow users to insert own enrollments" ON public.enrollments;
DROP POLICY IF EXISTS "Allow users to delete own enrollments" ON public.enrollments;
DROP POLICY IF EXISTS "Allow users to read own progress" ON public.progress;
DROP POLICY IF EXISTS "Allow users to insert own progress" ON public.progress;
DROP POLICY IF EXISTS "Allow users to update own progress" ON public.progress;
DROP POLICY IF EXISTS "Allow users to read own achievements" ON public.achievements;
DROP POLICY IF EXISTS "Allow admin read audit logs" ON public.audit_logs;
DROP POLICY IF EXISTS "Allow authenticated insert audit logs" ON public.audit_logs;

-- Policies for public reading
CREATE POLICY "Allow public read" ON public.roles FOR SELECT TO public USING (true);
CREATE POLICY "Allow public read" ON public.profiles FOR SELECT TO public USING (true);
CREATE POLICY "Allow public read" ON public.subjects FOR SELECT TO public USING (true);
CREATE POLICY "Allow public read" ON public.chapters FOR SELECT TO public USING (true);
CREATE POLICY "Allow public read" ON public.topics FOR SELECT TO public USING (true);
CREATE POLICY "Allow public read" ON public.lessons FOR SELECT TO public USING (true);
CREATE POLICY "Allow public read" ON public.lesson_versions FOR SELECT TO public USING (true);
CREATE POLICY "Allow public read" ON public.quizzes FOR SELECT TO public USING (true);
CREATE POLICY "Allow public read" ON public.questions FOR SELECT TO public USING (true);
CREATE POLICY "Allow public read" ON public.answers FOR SELECT TO public USING (true);

-- Profile self-update policy
CREATE POLICY "Allow users to update own profile" ON public.profiles
  FOR UPDATE TO authenticated USING (auth.uid() = id);

-- Enrollments policies
CREATE POLICY "Allow users to read own enrollments" ON public.enrollments
  FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Allow users to insert own enrollments" ON public.enrollments
  FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Allow users to delete own enrollments" ON public.enrollments
  FOR DELETE TO authenticated USING (auth.uid() = user_id);

-- Progress policies
CREATE POLICY "Allow users to read own progress" ON public.progress
  FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Allow users to insert own progress" ON public.progress
  FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Allow users to update own progress" ON public.progress
  FOR UPDATE TO authenticated USING (auth.uid() = user_id);

-- Achievements policies
CREATE POLICY "Allow users to read own achievements" ON public.achievements
  FOR SELECT TO authenticated USING (auth.uid() = user_id);

-- Audit logs policies (Admin read, authenticated insert)
CREATE POLICY "Allow admin read audit logs" ON public.audit_logs
  FOR SELECT TO authenticated USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid() AND profiles.role_name = 'admin'
    )
  );
CREATE POLICY "Allow authenticated insert audit logs" ON public.audit_logs
  FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);

-- Create a function to handle new user signups and metadata synchronization
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, email, username, full_name, avatar_url, role_name)
  VALUES (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'username', split_part(new.email, '@', 1)),
    coalesce(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name', ''),
    coalesce(new.raw_user_meta_data->>'avatar_url', new.raw_user_meta_data->>'picture', ''),
    'student'
  )
  ON CONFLICT (id) DO UPDATE
  SET
    email = excluded.email,
    username = coalesce(excluded.username, profiles.username),
    full_name = excluded.full_name,
    avatar_url = excluded.avatar_url,
    updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Create a trigger that calls the function on auth.users insert or update
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT OR UPDATE OF email, raw_user_meta_data ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
