-- ═══════════════════════════════════════════════════════════════════════
-- TIXAR MASTER DATABASE SCHEMA & SECURITY MIGRATION (V2)
-- Idempotent & safe to run multiple times in Supabase SQL Editor
-- ═══════════════════════════════════════════════════════════════════════

-- ==========================================================
-- 1. HISTORICAL QUESTION ATTEMPTS
-- ==========================================================
CREATE TABLE IF NOT EXISTS public.question_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL
        REFERENCES public.profiles(id)
        ON DELETE CASCADE,
    question_id BIGINT NOT NULL
        REFERENCES public.questions(id)
        ON DELETE CASCADE,
    topic_id BIGINT
        REFERENCES public.topics(id)
        ON DELETE SET NULL,
    user_answer TEXT,
    is_correct BOOLEAN NOT NULL,
    score NUMERIC DEFAULT 0,
    time_spent_seconds INTEGER,
    attempted_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL
);

-- ==========================================================
-- 2. DIAGNOSTIC MISTAKE INTELLIGENCE
-- ==========================================================
CREATE TABLE IF NOT EXISTS public.user_mistakes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL
        REFERENCES public.profiles(id)
        ON DELETE CASCADE,
    question_attempt_id BIGINT
        REFERENCES public.question_attempts(id)
        ON DELETE CASCADE,
    question_id BIGINT
        REFERENCES public.questions(id)
        ON DELETE SET NULL,
    topic_id BIGINT
        REFERENCES public.topics(id)
        ON DELETE SET NULL,
    topic_title TEXT,
    chapter_id BIGINT
        REFERENCES public.chapters(id)
        ON DELETE SET NULL,
    chapter_key TEXT,
    question_index INTEGER DEFAULT 0,
    question_text TEXT,
    correct_answer TEXT,
    solution TEXT,
    mistake_type TEXT,
    diagnostic_data JSONB DEFAULT '{}'::jsonb,
    resolved BOOLEAN DEFAULT FALSE,
    resolved_at TIMESTAMP WITH TIME ZONE,
    attempt_count INTEGER DEFAULT 1,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL
);

-- Ensure diagnostic_data column exists on user_mistakes
ALTER TABLE public.user_mistakes
    ADD COLUMN IF NOT EXISTS question_attempt_id BIGINT REFERENCES public.question_attempts(id) ON DELETE CASCADE,
    ADD COLUMN IF NOT EXISTS diagnostic_data JSONB DEFAULT '{}'::jsonb,
    ADD COLUMN IF NOT EXISTS chapter_id BIGINT REFERENCES public.chapters(id) ON DELETE SET NULL;

-- ==========================================================
-- 3. SPACED REPETITION REVIEWS
-- ==========================================================
CREATE TABLE IF NOT EXISTS public.spaced_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL
        REFERENCES public.profiles(id)
        ON DELETE CASCADE,
    topic_id BIGINT NOT NULL
        REFERENCES public.topics(id)
        ON DELETE CASCADE,
    topic_title TEXT,
    subject_id TEXT
        REFERENCES public.subjects(id)
        ON DELETE SET NULL,
    chapter_id BIGINT
        REFERENCES public.chapters(id)
        ON DELETE SET NULL,
    next_review_at TIMESTAMP WITH TIME ZONE NOT NULL,
    interval_days INTEGER DEFAULT 1,
    repetitions INTEGER DEFAULT 0,
    ease_factor NUMERIC DEFAULT 2.5,
    last_reviewed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT unique_user_topic_spaced UNIQUE(user_id, topic_id)
);

-- ==========================================================
-- 4. USER NOTES
-- ==========================================================
CREATE TABLE IF NOT EXISTS public.user_notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL
        REFERENCES public.profiles(id)
        ON DELETE CASCADE,
    topic_id BIGINT
        REFERENCES public.topics(id)
        ON DELETE SET NULL,
    topic_title TEXT,
    subject_id TEXT
        REFERENCES public.subjects(id)
        ON DELETE SET NULL,
    chapter_id BIGINT
        REFERENCES public.chapters(id)
        ON DELETE SET NULL,
    note_text TEXT DEFAULT '',
    content TEXT DEFAULT '',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL
);

-- ==========================================================
-- 5. BEHAVIORAL LEARNING EVENTS (TELEMETRY)
-- ==========================================================
CREATE TABLE IF NOT EXISTS public.learning_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL
        REFERENCES public.profiles(id)
        ON DELETE CASCADE,
    event_type TEXT NOT NULL,
    subject_id TEXT
        REFERENCES public.subjects(id)
        ON DELETE SET NULL,
    chapter_id BIGINT
        REFERENCES public.chapters(id)
        ON DELETE SET NULL,
    topic_id BIGINT
        REFERENCES public.topics(id)
        ON DELETE SET NULL,
    question_id BIGINT
        REFERENCES public.questions(id)
        ON DELETE SET NULL,
    client_event_id TEXT,
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_learning_events_client_event_id
ON public.learning_events(client_event_id)
WHERE client_event_id IS NOT NULL;

-- ==========================================================
-- 6. EXTEND PROGRESS AS THE MASTERY RECORD
-- ==========================================================
ALTER TABLE public.progress
    ADD COLUMN IF NOT EXISTS topic_title TEXT,
    ADD COLUMN IF NOT EXISTS subject_id TEXT
        REFERENCES public.subjects(id)
        ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS chapter_id BIGINT
        REFERENCES public.chapters(id)
        ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS confidence_level TEXT
        CHECK (confidence_level IN ('low', 'medium', 'high')),
    ADD COLUMN IF NOT EXISTS mastered BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS mastered_at TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS mastery_score NUMERIC DEFAULT 0,
    ADD COLUMN IF NOT EXISTS last_studied_at TIMESTAMP WITH TIME ZONE;

-- Safely add unique constraint on progress(user_id, topic_id) if not present
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'progress_user_id_topic_id_key'
    ) THEN
        ALTER TABLE public.progress ADD CONSTRAINT progress_user_id_topic_id_key UNIQUE (user_id, topic_id);
    END IF;
EXCEPTION
    WHEN duplicate_table THEN NULL;
    WHEN others THEN NULL;
END $$;

-- ==========================================================
-- 7. ROW LEVEL SECURITY (RLS) POLICIES
-- ==========================================================
ALTER TABLE public.progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.question_attempts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_mistakes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.spaced_reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.learning_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.achievements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.enrollments ENABLE ROW LEVEL SECURITY;

-- Clean conflicting policies and apply single-principle isolation
DROP POLICY IF EXISTS "Users isolated progress" ON public.progress;
DROP POLICY IF EXISTS "Users isolated progress all" ON public.progress;
CREATE POLICY "Users isolated progress all" ON public.progress
    FOR ALL TO authenticated
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users isolated attempts all" ON public.question_attempts;
CREATE POLICY "Users isolated attempts all" ON public.question_attempts
    FOR ALL TO authenticated
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users isolated mistakes all" ON public.user_mistakes;
CREATE POLICY "Users isolated mistakes all" ON public.user_mistakes
    FOR ALL TO authenticated
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users isolated spaced_reviews all" ON public.spaced_reviews;
CREATE POLICY "Users isolated spaced_reviews all" ON public.spaced_reviews
    FOR ALL TO authenticated
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users isolated user_notes all" ON public.user_notes;
CREATE POLICY "Users isolated user_notes all" ON public.user_notes
    FOR ALL TO authenticated
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users isolated learning_events all" ON public.learning_events;
CREATE POLICY "Users isolated learning_events all" ON public.learning_events
    FOR ALL TO authenticated
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users isolated achievements all" ON public.achievements;
CREATE POLICY "Users isolated achievements all" ON public.achievements
    FOR ALL TO authenticated
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users isolated enrollments all" ON public.enrollments;
CREATE POLICY "Users isolated enrollments all" ON public.enrollments
    FOR ALL TO authenticated
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

-- ==========================================================
-- 8. PERFORMANCE INDEXES FOR READINESS ENGINE
-- ==========================================================
CREATE INDEX IF NOT EXISTS idx_question_attempts_user ON public.question_attempts(user_id);
CREATE INDEX IF NOT EXISTS idx_question_attempts_topic ON public.question_attempts(topic_id);
CREATE INDEX IF NOT EXISTS idx_question_attempts_attempted_at ON public.question_attempts(attempted_at);
CREATE INDEX IF NOT EXISTS idx_user_mistakes_user ON public.user_mistakes(user_id);
CREATE INDEX IF NOT EXISTS idx_spaced_reviews_user_topic ON public.spaced_reviews(user_id, topic_id);
CREATE INDEX IF NOT EXISTS idx_learning_events_user_created ON public.learning_events(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_progress_user_topic ON public.progress(user_id, topic_id);

-- ==========================================================
-- 9. VERIFY POLICIES
-- ==========================================================
SELECT schemaname, tablename, policyname, roles, cmd
FROM pg_policies
WHERE schemaname = 'public'
ORDER BY tablename, policyname;
