const fs = require("fs");
const path = require("path");
const { loadCanonicalCurriculum } = require("./curriculumLoader");

const FRONTEND_DATA_DIR = path.resolve(__dirname, "../../frontend/src/data");

console.log("[generate_frontend_topics] Loading canonical curriculum from backend data...");
const { stats, contentMap } = loadCanonicalCurriculum();
console.log(`[generate_frontend_topics] Loaded ${contentMap.size} topics (${stats.questionsCount} questions).`);

const SUBJECTS = ["math", "physics", "chemistry", "biology", "english", "computer"];
const topicsBySubject = {};
for (const sid of SUBJECTS) {
  topicsBySubject[sid] = [];
}

for (const [key, val] of contentMap.entries()) {
  const sid = val.sid;
  if (!topicsBySubject[sid]) {
    console.warn(`[generate_frontend_topics] Unknown subject id: ${sid}`);
    continue;
  }

  topicsBySubject[sid].push({
    id: `${val.sid}|${val.cid}|${val.topic}`,
    curriculum_id: val.sid,
    chapter_id: val.cid,
    topic: val.topic,
    data: {
      notes: val.notes,
      qs: val.qs,
    },
    version: 2,
    is_deleted: false,
  });
}

for (const sid of SUBJECTS) {
  const list = topicsBySubject[sid];
  const targetFile = path.join(FRONTEND_DATA_DIR, `${sid}.js`);
  const content = `/**
 * Canonical Bundled Content: ${sid.toUpperCase()}
 * Auto-generated by backend/scripts/generate_frontend_topics.js
 * Total Topics: ${list.length}
 */

export const ${sid}Topics = ${JSON.stringify(list, null, 2)};

export default ${sid}Topics;
`;

  fs.writeFileSync(targetFile, content, "utf8");
  console.log(`[generate_frontend_topics] Wrote ${list.length} topics to ${targetFile}`);
}

console.log("[generate_frontend_topics] All subject chunks generated successfully.");
