-- ==============================================================================
-- TIXAR LEARNING INTELLIGENCE SYSTEM — PHASE P0 MIGRATION
-- Migration: 20260906_evidence_ledger_and_health.sql
-- Invariants: Tixar Intelligence Law (Reproducibility & Immutable Provenance)
-- ==============================================================================

-- 1. Immutable Evidence Ledger: Records exact evidence snapshots and rules for every recommendation
CREATE TABLE IF NOT EXISTS public.intelligence_decisions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    decision_type TEXT NOT NULL,          -- 'PREREQUISITE_GAP', 'CALIBRATING', 'READY_TO_ADVANCE', 'NO_ACTION', etc.
    action_type TEXT NOT NULL,            -- 'PRACTICE', 'DIAGNOSTIC_TEST', 'REPAIR_PREREQUISITE', 'NO_ACTION', 'SPACED_REVIEW'
    target_skill_id TEXT,
    target_topic_id BIGINT REFERENCES public.topics(id) ON DELETE SET NULL,
    target_topic_title TEXT NOT NULL,

    -- Epistemological Separation: Evidence Strength != Mastery != Readiness
    evidence_strength NUMERIC NOT NULL,   -- 0 to 100 (Volume, Consistency, Diversity, Recency)
    confidence_level TEXT NOT NULL,       -- 'LOW', 'MODERATE', 'HIGH'
    mastery_state TEXT NOT NULL,          -- 'UNKNOWN', 'INSUFFICIENT_EVIDENCE', 'EMERGING', 'ESTABLISHED', 'VERIFIED'
    readiness_state TEXT NOT NULL,        -- 'NOT_READY', 'READY', 'ADVANCED'

    -- Complete Evidence Snapshot at Decision Time T0 (Permanent Historical Reproducibility)
    evidence_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,  -- { totalAttempts, correctAttempts, accuracy, recentScores, recencyDays }
    evidence_refs JSONB NOT NULL DEFAULT '[]'::jsonb,      -- Array of original client_event_id strings
    inference_rules JSONB NOT NULL DEFAULT '[]'::jsonb,    -- Array of rule strings, e.g. ["MIN_ATTEMPTS_5", "ACCURACY_LT_40"]
    contributing_hypotheses JSONB DEFAULT '[]'::jsonb,     -- Heuristic weights: [{ factor: "factorisation", evidenceWeight: 0.78 }]
    explanation_payload JSONB NOT NULL DEFAULT '{}'::jsonb, -- Human-facing "Why?" breakdown

    -- Decision Lifecycle: Append-only supersession (Decision #1842 is never modified; Decision #1901 supersedes it)
    supersedes_decision_id BIGINT REFERENCES public.intelligence_decisions(id) ON DELETE SET NULL,

    -- Engine & Rule Versions for strict historical reproducibility
    engine_version TEXT NOT NULL DEFAULT '2.0.0',
    rule_version INTEGER NOT NULL DEFAULT 1,
    schema_version INTEGER NOT NULL DEFAULT 1,

    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_intelligence_decisions_user_created 
ON public.intelligence_decisions(user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_intelligence_decisions_superseded 
ON public.intelligence_decisions(supersedes_decision_id);

-- True Immutability Guard: Database-level trigger forbidding UPDATE and DELETE
CREATE OR REPLACE FUNCTION public.prevent_intelligence_decision_mutation()
RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION 'intelligence_decisions is an immutable ledger. Updates and deletions are prohibited. Append a new decision with supersedes_decision_id instead.';
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_prevent_intelligence_decision_mutation ON public.intelligence_decisions;
CREATE TRIGGER trg_prevent_intelligence_decision_mutation
BEFORE UPDATE OR DELETE ON public.intelligence_decisions
FOR EACH ROW EXECUTE FUNCTION public.prevent_intelligence_decision_mutation();

-- 2. Telemetry Ingestion Health & Observability Metrics
CREATE TABLE IF NOT EXISTS public.telemetry_health_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_size INTEGER NOT NULL,
    valid_events_count INTEGER NOT NULL,
    rejected_events_count INTEGER NOT NULL,
    duplicates_suppressed INTEGER NOT NULL,
    unresolved_topics_count INTEGER NOT NULL,
    user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    rejection_reasons JSONB DEFAULT '{}'::jsonb,
    recorded_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_telemetry_health_recorded 
ON public.telemetry_health_logs(recorded_at DESC);
